# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb1103ae35b38c5142b4de3a8ed83ac8ae838f8940f3742fdc931ebd10ba322889158f4e146abdb5940cae0bdb546f07a94401ae383f245b138f6537f08d578a
  google_client_id: 314472384995-baptkkpnp79nm4rkpsd7fp4dus5legbg.apps.googleusercontent.com
  google_client_secret: 1MnjOIP927XheaTg0X8NEian


test:
  secret_key_base: 160e178e33f15b150c8f8c9691704083581bd185964c063cf21cb41bca896ac908cf5d00bbfd35f901410cc27f32bb1e713a8e941f570f1c89664d11630b92b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>